### PR TITLE
add basic latex support

### PR DESCRIPTION
**Pull request by robbielyman**
I use Markdown (well, Kramdown I suppose) for writing blog posts involving math. For this reason, LaTeX injection makes the most sense for me when controlled by a pair of `$$`. I took a basic stab at adding this to the `markdown-inline` parser.

Currently having an unclosed `$$` is an error; I imagine this is not desirable?

Unrelatedly, any hints about being able to *test* this parser in neovim, which complains about "invalid node type at position 21 for language markdown_inline" would be most welcome.

### CODE REVIEW

**Comment by robbielyman** [comment]
ah, for testing: compiling `nvim` with `USE_BUNDLED_TS_PARSERS=0` works; neat! :smile:

EDIT: huh, somehow I cannot manage to consistently trigger `latex` injection unless (and this is so confusing to me) there is a `latex` tag in the first paragraph of the file (not counting something like a bit of `yaml` at the top).
My `queries/injections.scm` file looks like this, so it presumably should work just fine.

```lisp
((html_tag) @html)
((latex) @latex)
```

**Comment by MDeiml** [comment]
Oh I am very sorry, I somehow missed this pull request. Of course I would love to see this merged. Do you still want to work on this? Otherwise I could take over.

There's two nitpicks I have:
1. The markdown grammar should never produce `(ERROR)` since there is no such thing as invalid markdown. In the context of this pull request that means that for something like
   ```markdown
   $$x$$y$$
   ```
   The output should mark `$$x$$` as latex and `y$$` as normal text. So no `ERROR` nodes.

   I guess this would probably make the implementation quite a bit more complicated, but you should be able to basically copy the code for `code_span` in `tree-sitter-inline/grammar.js` and `tree-sitter-inline/src/scanner.cc`. (I apologize in advance for the terrible sphagetti code in `scanner.cc`).
2. Since there is no "one-true markdown" I made this parser configurable by, see the beginning of `common/grammar.js`. If you want I could do that for you though.

**Comment by robbielyman** [comment]
~~I don't think it's quite ready yet. In particular I'm confused by the new presence of `(MISSING latex_span_delimiter)` in some of the tests (particularly example 671) when there is only one `$` present,
since those nodes don't appear for code blocks, which I was attempting to mimic.~~

aha, I was missing an instance of `_code_block_delimiter`.

I couldn't quite understand how to add configuration; any hints or help there would definitely be welcome.

**Comment by MDeiml** [comment]
Thanks a lot, that was fast! Looks good already

Yeah sorry, I did not get around to documenting this yet.

In the beginning of `common/grammar.js` you just add another line sth like
```js
exports.EXTENSION_LATEX = process.env.EXTENSION_LATEX | exports.EXTENSION_DEFAULT
```
This makes it so this feature can be activated using the `EXTENSION_LATEX` envvar, but it will also be active by default.

Then in `tree-sitter-markdown-inline/grammar.js` you will have to use the now defined `exports.EXTENSION_LATEX`: In the definition of `_inline_base` and `_text_inline_no_link` you replace `$.latex_block` and `$._latex_span_start` with `(exports.EXTENSION_DEFAULT ? $.latex_block : choice())` and similar. That will make it so that latex is only parsed when the `EXTENSION_LATEX` feature is active. Maybe a few errors will come up about things being undefined, you should be able to solve them in the same way.

**Comment by robbielyman** [comment]
that was easy enough, thanks for the pointers!

**Comment by MDeiml** [comment]
Looks good now :) . There are some conflicts, so it would be best if you rebased the PR, but otherwise it's ready to merge.

**Comment by robbielyman** [comment]
I think the rebasing went okay? it looks like the conflicts are gone at least.

**Comment by MDeiml** [comment]
Yes, looks all goods. Tests are passing too. It just seems the grammar wasn't compiled correctly. Can you try running `npm run build` in the root directory and pushing again?

**Comment by robbielyman** [comment]
`node-gyp` complained at me about needing to run configure first, maybe it would be good to add that to the build script?

**Comment by MDeiml** [comment]
> `node-gyp` complained at me about needing to run configure first, maybe it would be good to add that to the build script?

Huh, that's new to me, I'm going to open an issue for that

Thanks a lot for this implementation. Quite a few people will be happy about this I think.

**Pull request merged**
