### PR TITLE
Revert "Add Swift accessors for scm resources"

### PR DESCRIPTION
**Pull request by jsorge**
I was discussing this with @mattmassicotte just after I opened the PR and he's concerned this is going to break a lot of clients in the wild because of the change to the Swift packages here, so it sounds like it's best to revert for now.

So sorry!

### CODE REVIEW

**Comment by MDeiml** [comment]
Sorry from my side too. Should have waited for your answer.

**Comment by MDeiml** [comment]
Is there a safe way for doing this though?

**Comment by mattmassicotte** [comment]
Just to add some context - I love the idea of this change. The issue is this makes the markdown parser special in a way that a) will break existing users and b) will be a lot of work to copy to other SPM-enabled parsers. So, while this is good, I think it makes more sense to keep the binding very uniform and move special logic into higher-levels.

**Comment by MDeiml** [comment]
Ok. Thanks for your insight

**Pull request merged**
